### PR TITLE
Generate pkgconfig file for tidy

### PR DESCRIPTION
**Pull request by spk**
This allow to generate pkgconfig file from cmake for tidy

### CODE REVIEW

**Comment by geoffmcl** [comment]
@spk thanks for this PR... we like those...

But please remind me why we **need** a pkgconfig file... Working mainly in Windows, it seems this is not required, or used there... but...

And it seems you have only added it to the CPack package config... that is if a DEB/RPM/... is generated. What about a normal build and install from source?

However, it also seems no harm, so if no negative comments, will merge this in a few days... thanks...

**Comment by spk** [comment]
Hi @geoffmcl thanks for the feedback
The pkgconfig file is useful for people or tools that need to find information about the libs or headers; like the path of the `tidy.h` on the system with for example `pkg-config --cflags tidy` give for me `-I/usr/local/include`
I found an issue with the Debian package with your information; currently going to `/usr/local` where for Debian its a violation of the policy, I will make a fix soon

**Comment by balthisar** [comment]
Seems okay by me.

**Comment by spk** [comment]
@geoffmcl @balthisar I found a fix with pkgconfig with packages in 3333ca7 let me know what you think?

**Comment by geoffmcl** [comment]
@spk thank you for the update...

However, as a mainly Windows person, where this `pkgconfig` change is **never** used, I think?, then I am **not** the person to decide on this...

One comment against `currently going to "/usr/local" where for Debian its a violation of the policy`, when working with the **last** Debian update - a very **long** and **arduous** process - I got the **opposite** impression... but what do I know...

See https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623, and https://launchpad.net/ubuntu/+source/tidy-html5 - added Tidy 5.2.0...

**Especially** see Issue #354, and maybe others, for more on this **Debian** process... with @AdamMajer, @danielhjames, @jasonethomas, @mcandre, and we urge them to update to release Tidy 5.4.0... when they get the chance...

And maybe during the **Debian** package creation, this was already done... I do not know...

For sure, CMake defaults to `/usr/local` if **no** `-DCMAKE_INSTALL_PREFIX=<path>` is given... that is **known**...

Simply, if this is ok by @balthisar, in OS X, a *nix type OS, then for sure I have no problem with this... thanks...

**Comment by balthisar** [comment]
@geoffmcl, @spk, from the Mac perspective but _not_ as a pkg-config user, I'm okay with this. The default `make install` isn't broken, and the only difference is the include headers are now in a subdirectory (but still within the default header search path).

However, when attempting to `make package` I encounter this error on macOS:

`CPack Error: Cannot initialize CPack generator: PackageMaker`.

This makes sense. PackageMaker on macOS is long-deprecated. Let me see if I can find out how to tell CMake to use the current tools, or at least put in a guard for macOS prior to merging this.

**Comment by balthisar** [comment]
Okay, I found the macOS issue, so I'll merge this and then apply the macOS fix.

**Comment by AdamMajer** [comment]
There should be no problem with this change for any Linux distribution. If they don't need it, they will just not distribute the .pc file.

**Comment by spk** [comment]
Great, thanks !

**Pull request merged**
