### PR TITLE
style: ansi conforming comments

### PR DESCRIPTION
**Pull request by marcoscaceres**
Makes compiling a little bit less noisy when compiling on *nix with `-ansi` option is set. Also now adheres to projects commenting conventions.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Still getting noise from:
```bash
tidy-html5/src/message.c:233:9: warning: implicit declaration of function 'va_copy'
      [-Wimplicit-function-declaration]
        va_copy(args_copy, args);
        ^
1 warning generated.
```

A lot of noise from ones like this:

```bash
tidy-html5/src/language_en.h:109:9: warning: string literal of length 847 exceeds
      maximum length 509 that C90 compilers are required to support [-Woverlength-strings]
```

And this one is interesting too, as it uses a modern C99 feature?:

```
tidy-html5/src/language.c:30:25: warning: flexible array members are a C99 feature
      [-Wc99-extensions]
    languageDefinition *languages[];
```
(see also tidy-html5/src/language.c:30:25)

**Comment by geoffmcl** [comment]
@marcoscaceres, wow, we have let things slip in this regard...

By the time I came back to tidy, I guess some of these `slips` had been done...

But is it the time to **reject** all the compiler advances since the `-ansi` option?

You have quite rightly highlighted many instances of where tidy has slipped a little... but are these wrong? Some maybe need to be looked at...

On the **single** issue of inline comments `//`, versus **only** `/* ... */`, I am very ambivalent... I do not see a problem accepting `//`... but that is just my view... 

Code I write at the moment exclusively uses `/*\ ... \*/`, but that is a **style** I have adopted for **tidy**...

Look forward to further comments... thanks...

**Comment by marcoscaceres** [comment]
I don't mind so much, but the problem is when building the first time with "-ansi -pedantic" it generates a lot of noise because of the comments and string literals that exceed 509 bytes (related to #460). 
 
Also note that `languageDefinition *languages[];` is already in violation of c89 (and tidy has been shipping that for a while, I assume) - so trying to compile with c89 breaks the linker. 

So, this again raises the question about which c standard version to use (#460). Again, I'm really new to c, but It appears there is enough code currently in the project to say that this is a "c99"-conforming project. 

As someone who knows the code really well, could you maybe evaluate what is the right standard to use?

**Comment by geoffmcl** [comment]
See #450 for additional comment...

Will try to pull and test this... thanks...

**Comment by geoffmcl** [comment]
@marcoscaceres have now carefully reviewed your `ansi_compliance` branch, and this all looks good... 

Can you `rebase` your fork to master to ensure there are no conflicts, and will merge this... thanks...

**Comment by marcoscaceres** [comment]
@geoffmcl rebased. Thank you for the review.

**Comment by geoffmcl** [comment]
@marcoscaceres sorry for the brief delay... 

Are we still good to go on this?

**Comment by marcoscaceres** [comment]
Should be all good to merge.

**Comment by geoffmcl** [comment]
Done, and thanks...

**Pull request merged**
