### PR TITLE
Tidy doc cleanup

### PR DESCRIPTION
**Pull request by balthisar**
Lots of exciting changes!
- Elimination of build/documentation/.
- All documentation source files, build, etc., in documentation/
- CMakelists.txt updated to use correct /documentation/ files
- Other help build scripts use /documentation/ files.
- localize.c dead links purged.
  - new http://www.html-tidy.org/accessibility/ page on our domain "rescues" one of the dead links.
- XSL's updated to support more legible man pages and quickref.html
- build_docs.sh processes quickref.html through Tidy because, well, it _should_.
- Option descriptions in localize.c have gone through many changes:
  - New &lt;br/> support in XSL makes man/quickref more legible, so I sprinkled them liberally throughout.
  - Lower-case all HTML elements.
  - Consistent use of &lt;code> to emphasize option names, option values, tags, etc.
  - Clarified the interaction of options such as indent-spaces, etc.
  - @geoffmcl's proposed new wording from #65.
- Consolidation of all readmes, licenses, etc., into README/

Issuing as a PR as I don't want to merge without someone else's review.

### CODE REVIEW

**Comment by geoffmcl** [comment]
@balthisar yes, there are a lot of exciting changes... thanks...

I have review all changes, but only looked mainly for code changes. In other words I did not fully check all the new decsriptions, words, syntax, etc, ... but all that I did read made sense... and of course it still compiles without a problem...

Also have not yet got around to trying an API documentation build, since I may need a change to the script I use, but I will get around to that... I am sure you have done this several times...

So I think this should be merged to `master`, and the version bumped to 5.1.18, with a correspond date change. I know most of these are not code changes, but if someone now reports an error in a description we need to know they are reading the new descriptions...

Of course, as expected, the removal of the dead `bobby` link, which is good, does cause about a dozen message files, generated from `./testall.sh`, to be different from those in `testbase`... but it is only message file changes... so after this merge, we also need to update `testbase` with the new messages...

There are 2 other message file differences NOT related to your changes - test 431895 `(./ diff)`, and test 443678 `(3 to 2 warnings)` that I have been trying to `solve`. In 431895 I think the leading `./` difference comes from the different scripts, but still to track down which and change it, then decide which should be in `testbase`, and 443678 seems a good desired change, but again still to explore it exactly... and see some other discussion on changes in #266...

But these other changes are not related to your pushes, so, as stated I think it should be merged... again, thanks... lots of work went into this...

**Comment by balthisar** [comment]
Pushed as-is and bumped version and date.


On Tue, Nov 3, 2015 at 2:08 AM, Geoff McLane <notifications@github.com>
wrote:

> @balthisar <https://github.com/balthisar> yes, there are a lot of
> exciting changes... thanks...
>
> I have review all changes, but only looked mainly for code changes. In
> other words I did not fully check all the new decsriptions, words, syntax,
> etc, ... but all that I did read made sense... and of course it still
> compiles without a problem...
>
> Also have not yet got around to trying an API documentation build, since I
> may need a change to the script I use, but I will get around to that... I
> am sure you have done this several times...
>
> So I think this should be merged to master, and the version bumped to
> 5.1.18, with a correspond date change. I know most of these are not code
> changes, but if someone now reports an error in a description we need to
> know they are reading the new descriptions...
>
> Of course, as expected, the removal of the dead bobby link, which is
> good, does cause about a dozen message files, generated from ./testall.sh,
> to be different from those in testbase... but it is only message file
> changes... so after this merge, we also need to update testbase with the
> new messages...
>
> There are 2 other message file differences NOT related to your changes -
> test 431895 (./ diff), and test 443678 (3 to 2 warnings) that I have been
> trying to solve. In 431895 I think the leading ./ difference comes from
> the different scripts, but still to track down which and change it, then
> decide which should be in testbase, and 443678 seems a good desired
> change, but again still to explore it exactly... and see some other
> discussion on changes in #266
> <https://github.com/htacg/tidy-html5/issues/266>...
>
> But these other changes are not related to your pushes, so, as stated I
> think it should be merged... again, thanks... lots of work went into this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/pull/289#issuecomment-153104699>.
>



-- 
---
Jim Derry
Clinton Township, MI, USA
Nanjing, Jiangsu, China PRC

**Comment by geoffmcl** [comment]
@balthisar thanks muchly...

Pushed a small C/C++ crossover problems, that gcc has been allowing for FOREVER!, but fails with compilers that still honor this K&R (pure) C rule... nothing really...

**Comment by balthisar** [comment]
I used to prefer the K&R way of doing things, but as I said I'm still
trying to shake my modern habits. :-)

I was having trouble getting indent-with-tabs to work using `libtidy` and
`tidyOptSetBool` directly so I posted a PR for review.

https://github.com/htacg/tidy-html5/tree/fix_indent_with_tabs_for_libtidy

I will answer email shortly!


On Wed, Nov 4, 2015 at 9:55 AM, Geoff McLane <notifications@github.com>
wrote:

> @balthisar <https://github.com/balthisar> thanks muchly...
>
> Pushed a small C/C++ crossover problems, that gcc has been allowing for
> FOREVER!, but fails with compilers that still honor this K&R (pure) C
> rule... nothing really...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/pull/289#issuecomment-153546332>.
>



-- 
---
Jim Derry
Clinton Township, MI, USA
Nanjing, Jiangsu, China PRC

**Pull request merged**
