### PR TITLE
Issue 329

### PR DESCRIPTION
**Pull request by geoffmcl**
Issue #329 - Proposed merge of issue-329 to master after rebasing to master

Edit: Please excuse the messy commit record, while I learned more about rebasing...

### CODE REVIEW

**Comment by geoffmcl** [comment]
**Warning**: This could introduce some regressions! 

It allows a newline char to be fetched from the stream. This does wonders to correctly rendered as `<p>a <em>b></em></p>` from -

```
<p>a<em>
b</em></p>
```

Note the newline has been replaced with a space, and moved to before the `<em>`, making it render correctly in browsers, but this newline can then also move some things down in output. This will mostly not effect the browser display, but becomes a pretty print problem of not trimming leading spacey chars...

I think some further work is needed to complete this fix before merging!

**Comment by geoffmcl** [comment]
@balthisar would you be able to show me, help me, tidy up this branch? Get it back to just one fix... well maybe two separate items...

Is is sort of only one small fix, commit f3de815963, even without the debug line and col change, which can be dropped...

As stated this presently has other pretty print changes that are not good, but getting it back to a clean state, single fix, could help me move forward with that...

Maybe by writing a REBASE.md readme, and/or rebasing it, or something... thanks...

In other cases I have seen you are a wizard at getting rid of the development crud ;=))

And then I have confused it with a different issue commit 3e93d41b which should be in master anyway. It only avoids a warning output that should be done separately. Maybe cherry picking, which I have never tried... again hope you can help...

**Comment by balthisar** [comment]
Can do... do you want `issue-329` as-is, right now to be rebased against master, or a particular commit in `issue-329` rebased against master?

**Comment by balthisar** [comment]
@geoffmcl, this was weird and tricky, and I'm not really satisfied with the
results. To be pragmatic, it's working, but I completely lost your commit
history. On the other hand despite the fact that it took longer than simply
doing it manually would have, it was a learning experience, and I seldom
shy away from those!

When I tried a standard rebase there were a few other merges present, from
branches that no longer exist (apparently). Thus a true rebase failed for me.

This is what I tried (and should work for you in the future barring missing branches):

* * * *

First create a new branch. We shouldn’t push a rebased branch back to a public
repository. Assuming we're already in `issue_329`:

~~~
$git checkout -b issue-329_rebase
~~~

Just to be sure where we diverged, get SHA of that point:

~~~
$git merge-base master issue-329_rebase
8c13d270ede8d47b74b2373d818b2841f799ee23
~~~

To flatten this branch, I should be able to go back to this point. I like to
do this, interactively:

~~~
$git rebase -i 8c13d2
~~~

When you editor opens (mine is `nano`) leave the first line alone, then change
the remaining `pick`'s to `s` (meaning squash). You can read the other options.
Note that if you use `reword` don't reword now; the editor will open up again
for later rewording.

That failed, so I 

~~~
git rebase --abort
~~~

* * *

The issue I found during the rebasing session was that there were SHA's present
that I couldn't find anywhere, presumably from deleted branches. And so git 
wasn't able to replay these changes.

What I did, though, was

~~~
git reset --soft 8c13d2
~~~

Which kept the current changes, staged, but reset us to the diverging point.
Committed that and them pushed to Github.

* * *

There are still merge conflicts vs master, so let me see if this is easier now.

~~~
git merge master
~~~

Fix version.txt and push to 329_rebased_merged

I'll leave all three branches as they are. Given that this delete the commit
history, I suggest you pull issue-329, use the reset soft trick, yourself,
and if you're ready to put it into master, simply merge it. Feel free to delete
the _rebased branches; if you don't delete them I'll do it in a couple of days.

**Comment by geoffmcl** [comment]
@balthisar wow, thanks for the efforts... sorry it was so `weird and tricky`!

I think I understood some of what you did, and for sure the `329_rebased_merged` branch now correctly reflects the two simple fixes involved.

But these two things are totally unrelated to each other. But now they are clear and nicely separated and I will redo them again. They are very small...

The `parser.c`, issue #314 I will add to `master` soon. It is a good fix, and presents no problems.

The 'lexer.c', issue #329 is only a partial fix, and needs more attention, and I will maybe create a new clean `issue_329` branch for this, where I can work on it, especially now that we have our [tests](https://github.com/htacg/tidy-html5-tests/tree/refactor) repo looking good. It is `regressions` that I fear most about this fix! Now we have the tools...

Meantime, am closing this pull request as too much of a **mess**, and will eventually delete the issue-329 branch... and I think you can delete the two branches you created... Again thanks for your efforts on this... I think I learned something...

**Pull request closed without merging**
