### PR TITLE
vertical-space no means no vertical space

### PR DESCRIPTION
**Pull request by nokome**
This is attempt to implement :

> option to prevent outputting unnecessary vertical whitespace #163 (feature and pretty print) is a clear request that --vertical-space f mean almost NO vertical space ;=)) Sort of like a compact html stream - just one line" 

which also addresses:

> newlines inserted in pre tags #158 (feature and pretty print) is an old, OLD problem, still to be resolved

See htacg/tidy-html5#158, htacg/tidy-html5#163, htacg/tidy-html5#227.

With this, `--vertical-space no` outputs no new lines except those within pre, script and style tags (and possibly some others). Wrapping still applies, so if you really want no newlines then also specify `--wrap 0`. The default for  `vertical-space` has been changed to `yes` to be more similar to what it was (but really this might need to have a three level enum `none`, `classic`, `yes` to retain backwards compatibility). 

The `vertical-space` option currently also applies to the start and end newlines referred to in #158. But if people want that as a separate option (i.e. vertical spacing but no extra new lines in pre etc) then it should be fairly easy to add. Let me know.

This has not been fully tested; some basic tests below.

Input:
```html
<!DOCTYPE html>
<html>
	<head>
		<title>Flatland</title>
		<meta charset="utf-8">
	</head>
	<body>
		<div><div>Some like it flat</div></div>
		<pre>I want my
			newlines preserved.</pre>
		<style>
			.me.too {
				color: red;
			}
		</style>
		<script>I dont want any at all!</script>
		<p class="a long attribute that will get wrapped">
			A long piece of text that will get wrapped.
		</p>
	</body>
</html>
```

```sh
tidy test.html
```
```html
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.1.0.RC1">
<title>Flatland</title>
<meta charset="utf-8">
</head>
<body>
<div>
<div>Some like it flat</div>
</div>

<pre>
I want my
                        newlines preserved.
</pre>
<style>
                        .me.too {
                                color: red;
                        }
</style>
<script>
I dont want any at all!
</script>
<p class="a long attribute that will get wrapped">A long piece of
text that will get wrapped.</p>
</body>
</html>
```

```sh
tidy --vertical-space no --wrap 20 test.html
```
```html
<!DOCTYPE html><html><head><meta name=
"generator"
content="HTML Tidy for HTML5 for Linux version 5.1.0.RC1"><title>
Flatland</title><meta charset=
"utf-8"></head><body><div><div>Some like it
flat</div></div><pre>I want my
                        newlines preserved.</pre><style>                        .me.too {
                                color: red;
                        }
</style><script>I dont want any at all!</script><p class=
"a long attribute that will get wrapped">A long piece of
text that will get
wrapped.</p></body></html>
```

```sh
tidy --vertical-space no --wrap 0 test.html
```
```html
<!DOCTYPE html><html><head><meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.1.0.RC1"><title>Flatland</title><meta charset="utf-8"></head><body><div><div>Some like it flat</div></div><pre>I want my
                        newlines preserved.</pre><style>                        .me.too {
                                color: red;
                        }
</style><script>I dont want any at all!</script><p class="a long attribute that will get wrapped">A long piece of text that will get wrapped.</p></body></html>
```

### CODE REVIEW

**Comment by geoffmcl** [comment]
@nokome  wow, you have certainly made a good start... thanks...

What you have effected is `--vertical-space off` means almost NO vertical space! But is that exactly what we want? Maybe an enumeration might be better... or something...

Looking at the code the current  TidyVertSpace is just used 3 times -

 1. `<hr>` - horizontal rule
 2. `<pre>` and `<textarea>`
 3. container element, other tags

In each case you can read the simple comments `/* insert extra newline for classic formatting */`

And also the help text states, which is what is shown on `$ man tidy` page -

```
  {TidyVertSpace,
   "This option specifies if Tidy should add some empty lines for "
   "readability. "
  },
```

So, for sure, an additional part of this PR would need to `amend` this text appropriately... 

But in the enumeration, which is a comment that appears in doxygen docs generation... maybe it is already simple enough...

```
  TidyVertSpace,       /**< degree to which markup is spread out vertically */
```

So then, using the Bool we have -

It defaults to `no`, meaning you get lots of vertical space, even some undesirable like in the `<pre>...</pre>` case, and a `yes` means just add some extra `classic` vertical space, in a few special cases...

Hmmm, rather than a new special enum we could use the `TidyTriState` Autobool option - no,yes,auto... 

Then we have 3 states -

 1. TidyNoState,     `/**< maps to 'no' */`
 2. TidyYesState,    `/**< maps to 'yes' */`
 3. TidyAutoState    `/**< Automatic */`

Then `no` means output as now, with vertical spaces... `yes` means classic, add some extra vertical spaces...

And `auto` means give me the leanest version of tidy! That is almost **NO** vertical space... sort of compressed one line html... light and fast... modern...

Then the man page could read -
```
  {TidyVertSpace,
   "This option specifies if Tidy should add some empty lines for "
   "readability.  Default 'no'. If set to 'auto' Tidy will eliminate almost all vertical-space."
  },
```

### Issue #158 - newlines inserted in `<pre>` tags

To me the `<pre>...</pre>` is a separate and special issue, and maybe does not need to be related to this `vertical-space` option at all. 

To me `pre` means do **not** mess at all with my spacing. And that would mean avoiding a newline after a `<pre>` tag, unless one is in my text, and avoid a newline before the `</pre>` tag, again unless there is one in my text.

I think a strict application of this does not need an option. It is what Tidy should do in the html5 era ;=)) So think this should be a separate fix/PR... as always, any help appreciated...

### But back to this PR...

So I think it is not quite the right time to merge this PR into `master`, but have merged it into an `issue-226` branch to continue its development... you should be able to pull it into your fork, using rebase...

Anyway, what would be your, or of others, comments on the above ideas? 

You have done some very necessary ground work here, thanks again, and it seems more a case of how to present this extended 'option', and deal with the use cases... 

If you get a chance to continue this PR that would be great... I will help where I can...

**Comment by nokome** [comment]
My vote for `vertical-space` options is:

- `no` : no vertical spaces except explicit newlines in `<pre>`,`<script>`,`<style>` (and possibly some others?)
- `yes`: Tidy adds new lines between elements (the current `no` default)
- ` extra`: Tidy adds extra new lines for readability (the current `yes`)

This would obviously break backward compatibility for what `no` and `yes` mean for this option but is more reflective of the actual output.

Regarding, #158 newlines inserted in `<pre>`. I agree with the suggestion that this should not be an option and those extra newlines should not go in there. @camoy has given use PR #229 but that only addresses `<pre>` (?) and not `<script>` and `<style>`. Furthermore, I have noticed that with this PR and `vetical-space no`, if you want your `<pre>` tag to start with a newline (I often do) and put an explicit newline at the start of it, Tidy is stripping it out (in parsing somewhere?) - so you don't get out what went in. In short, probably needs more work than is in #229.

**Comment by geoffmcl** [comment]
@nokome ok, I could agree with your AutoBool enum wrapping, but as you point out this introduces backward compatibility to existing configs in use by (Zillions? ;=)) of users... 

Where as my mapping meant no change for anyone, except the new user, who wants to use your **new** feature, that is nearly **no** newlines...

So if we go to -

 - no : no vertical spaces except explicit newlines in `<pre>,<script>,<style>` (and possibly some others?)
 - yes : Tidy adds new lines between elements (the current no , current and new default)
 - auto : Tidy adds extra new lines for readability (the current yes == classic)

And assuming a changed `default` to `yes`, it does break some backward compatibility, and causes change! How much? If in their config -

 - No use of `--vertical-space` - no change for them. Hopefully the majority???
 - Uses `--vertical-space yes`  - need to change to `--vertical-space auto` (classic)
 - Uses `--vertical-space no`   - need to change - a really **BIG** surprise for them!!! ;=))

And of course no one would yet have `--vertical-space auto`, since it does not exist.

Compared with the current `default` of `no`, and using my mapping of -

  - no : output as now, with vertical spaces...
  - yes : means classic, add some extra vertical spaces...
  - auto : A **new** feature - almost **NO** vertical space...

If in their configs -

 - No use of `--vertical-space` - no change for them. Hopefully the majority???
 - Uses `--vertical-space yes`  - no change for them. They get the extra vertical space (classic) 
 - Uses `--vertical-space no`   - no change for them. They get the default...
 
And the **new** user, who wants the **new** compact html feature adds -

 - Use `--vertical-space auto`  - They get a bare output, with almost no newlines
 
So I am really 50:50 which mapping is used, but I suppose would fall on the side of maintaining backward compatibility. Need some more people to comment on this to decide...

Regarding, #158 newlines inserted in `<pre>`, as you may have seen have merged this. It deals with one small problem, now solved...

Concerning the fact that Tidy! `eats` any leading user newline, I would prefer you open a **new** issue for this!

This `loss` of a leading newline would be back in the parser/lexer building of the tree... nothing to do with pprint... I can confirm that 5.1.2 does this, and it is a **bug** in my book... might be easy to find, fix, ... but I haven't yet seen where... will probably be something to do with `GetTokenMode mode`, or in the post token collection in TrimSpaces( doc, element );... any help appreciated...

But here in this #228 have a potential **NEW** feature ;=)) Always welcome, and exciting... let's continue...

You will note the PR is no longer auto-mergeable... you need to rebase your fork... can help with this... and as mentioned this change is now in the issue-228 branch... so this PR has been used. Thanks...

Which way forward?

**Comment by geoffmcl** [comment]
@nokome since I found a potential solution I opened a new #230 specifically to deal with the `eaten` user newline in `<pre>` tag...

**Comment by nokome** [comment]
@geoffmcl , I am happy to defer to you, and backward compatibility, on this. I'll perhaps wait a few days in the hope of others chiming in, then take it forward.

**Comment by geoffmcl** [comment]
@nokome thanks for rebase? to master... but it seems you did not switch to the `issue-228` branch... but no problem...

Certainly, let's wait a few days to see if there is any further comments...

Meantime, agree and have added the `<style>` and `<script>` to my patch, and added this to this `issue-228` branch...

In this branch there are just 5 cases of `cfgBool( doc, TidyVertSpace );` to be changed to `cfgAutoBool`, and deal with the case switching, like ... 

```
    /* pseudo code - not used */
    TidyTriState vert_space = cfgAutoBool( doc, TidyVertSpace );
    Bool classic = no;
    Bool no_vert_space = no;
    switch (vert_space) {
    case TidyNoState:    /**< maps to 'no' */
        # nothing to change...
        break;
    case TidyYesState:    /**< maps to 'yes' */
        classic = yes;
        break;
    case TidyAutoState:    /**< Automatic */
    default: /* not sure this is required */
        no_vert_space = yes;
        break;
    }
```

And/Or this could be presented as macros -

```
/*\
 * Issue #228 20150715 - macros to access --vertical-space tri state configuration parameter
\*/
#define TidyClassicVS ((cfgAutoBool( doc, TidyVertSpace ) == TidyYesState) ? yes : no)
#define TidyAddVS ((cfgAutoBool( doc, TidyVertSpace ) == TidyAutoState) ? no : yes )
```

I have implemented these in the `issue-228` branch using the above MACROS... but have done no tested yet...

I think I missed `squashing` two `unwanted` newlines that I saw in commit #0bf0d85a of your fork... would like to look at this first rather than just removing some extra lines traditional tidy! added for readability... And this is unrelated to whether or not there is a leading newline in the users text data, which needs to be preserved in the lexer... maybe a separate issue even...

Added the xml tri-state text for this option... for `$ man tidy` help page...

If you get a chance to sync up with this branch, and run your tests...

So to me things are moving forward ;=))

**Comment by geoffmcl** [comment]
@nokome some test results using the `issue-228` branch, and your above test.html...

DEFAULT config - --tidy-mark no --show-info no

```
CONFIG = DEFAULT
<!DOCTYPE html>
<html>
<head>
<title>Flatland</title>
<meta charset="utf-8">
</head>
<body>
<div>
<div>Some like it flat</div>
</div>
<pre>
I want my
            newlines preserved.
</pre>
<style>

            .me.too {
                color: red;
            }
</style>
<script>
I dont want any at all!
</script>
<p class="a long attribute that will get wrapped">A long piece of
text that will get wrapped.</p>
</body>
</html>
```

```
CONFIG += --vertical-space yes
<!DOCTYPE html>
<html>
<head>
<title>Flatland</title>
<meta charset="utf-8">
</head>
<body>
<div>
<div>Some like it flat</div>
</div>

<pre>
I want my
            newlines preserved.
</pre>
<style>

            .me.too {
                color: red;
            }
</style>
<script>
I dont want any at all!
</script>
<p class="a long attribute that will get wrapped">A long piece of
text that will get wrapped.</p>
</body>
</html>
```

```
CONFIG += --vertical-space auto
<!DOCTYPE html><html><head><title>Flatland</title><meta charset="utf-8"></head><body><div><div>Some like it flat</div></div><pre>I want my
            newlines preserved.</pre><style>
            .me.too {
                color: red;
            }
</style><script>I dont want any at all!</script><p class="a long attribute that will get wrapped">A long piece of
text that will get wrapped.</p></body></html>
```

I think I forgot the role of `wrap` in the last test... yes, with `--wrap 0` the last line is one line...

So, what if anything is wrong with these 3 outputs?

 - no (default) = add vertical space as before
 - yes - (classic) = add some extra vertical space on certain element
 - auto - new one line feature, almost **NO** vertical space
 
Looks very good to me, but it is getting late, and tired eyes can 
miss lots of things ;=))

**Comment by nokome** [comment]
This looks good to me. Thanks. 

The only only issue I can see is the extra new lines in the pre, style and script. For example, now that the first newline is not getting eaten the above `<style>` starts with two blank lines in the second example.

I'm getting a bit confused as to what patches are in and what is out. My suggestion for how to proceed would be to merge this PR into master *without* the "newline eating patch" . Then open a new issue that address the starting (and ending) newlines in pre, style and script elements which would encompass:
- Your "User leading newline text content of pre is eaten!" #230
- My remove extra newlines at start of script and style stencila/tidy-html5@0bf0d85

**Comment by geoffmcl** [comment]
@nokome Yes, had missed the fix #158, a PR which happened after creating this branch... have re-implemented it here, adding some more comments, which will probably result in a conflict if and when this branch is merged back to master... but will deal with that then...

Also bumped the version to match master...

And, as stated, still `thinking` about extra newlines at start of script and style - stencila/tidy-html5@0bf0d85 patch - it looks ok, but... maybe these `extra` newlines should remain if in `classic` mode... What do you think?

Anyway for now, everything is current in this `issue-228` branch, ie all other patches are in, so will do some more testing...

It is beginning to feel like a complete implementation of your `smart` newline, which presently looks for `--vertical-space auto` to produce almost a single line html output... a **great** new feature ;=)) thanks...

**Comment by nokome** [comment]
Thanks @geoffmcl for youe efforts on this one, I'll try to find the time to do some testing on the `issue-228` branch and continue this discussion over at #231

**Comment by geoffmcl** [comment]
@nokome just opened issue #238 which seems related to this `issue-228` branch...

Have code one fix, but looking for a `better` way to do it..

**Comment by nokome** [comment]
@geoffmcl , I had a look at #238 but can't offer any immediate insights sorry

**Comment by geoffmcl** [comment]
@nokome seems you did have some immediate ideas ;=))

But it seems in your PR, if I am reading it correctly, removing the `PFlushLineSmart(...)` from the `PPrintScriptStyle(...)` permanently changes the `<script>` output, and would **shock** those of us who expect such a newline... whether I added it or not in the code...

That is -

```
<script>var a = 0;
</script>
```

should be output as -

```
<script>
var a = 0;
</script>
```

And I think you would need more to deal with the `<style>` tag which can also now suffer from this creeping newline syndrome ;=((

I have suggested another, far simpler patch in #238, and that is to revert a little of what we discussed above... only excepting the `<pre>` tag, which has already had the post PrintTag newline removed... and returning `<script>` and `<style>` to what they were...

Appreciate it if you get a chance to try it... it seems to keep the current Tidy! output in the default case, and still fully honor the new `auto` switch...

What do you think?

**Comment by geoffmcl** [comment]
@nokome have now merge branch `issue-228` into the `master`branch... look for to testing of this new feature...

Thank you for your efforts that brought all this about...

**Comment by nokome** [comment]
Thanks @geoffmcl for all your work on Tidy. Pleasure to be able to help out a little. Sorry I have been quiet on this of late...a few too many other things keeping me occupied.

**Pull request closed without merging**
