### PR TITLE
Issue #437 - re-use of 'wrap-php' option

### PR DESCRIPTION
**Pull request by geoffmcl**
Review, testing and feedback welcome... thanks...

### CODE REVIEW

**Comment by balthisar** [comment]
@geoffmcl, testing is okay, but see followup discussion in #437.

**Comment by balthisar** [comment]
@geoffmcl, I merged the others, but didn't merge this one in case you want to change the scope based on #437 additional discussion.

**Comment by geoffmcl** [comment]
@balthisar see **more** discussion in #437...

**Comment by Tommy-Strange-88** [comment]
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    CC0
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://www.facebook.com/natalie.przybilla.39">
    <span property="dct:title">Natalie Przybilla</span></a>
  has waived all copyright and related or neighboring rights to
  this work.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="DE" about="https://www.facebook.com/natalie.przybilla.39">
  Deutschland</span>.
</p>

**Comment by balthisar** [comment]
@geoffmcl, go for it. We can open inconsistencies as future issues. Yes, this is ad hoc, but let it happen. We can do logical engineering later.

**Comment by geoffmcl** [comment]
@balthisar ok, went for it ;=))

**Pull request merged**
